/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgeRangeRouteImport } from './routes/age-range'
import { Route as ChangeDetailsRouteImport } from './routes/change-details'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as JourneyStageRouteImport } from './routes/journey-stage'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding-step-3'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding-step-4'
import { Route as TransitionRouteImport } from './routes/transition'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ChangeDetailsIndexRouteImport } from './routes/change-details.index'
import { Route as ChangeDetailsDietaryChangesRouteImport } from './routes/change-details.dietary-changes'
import { Route as ChangeDetailsPhysicalActivityRouteImport } from './routes/change-details.physical-activity'
import { Route as ChangeDetailsSleepRoutineRouteImport } from './routes/change-details.sleep-routine'
import { Route as ChangeDetailsSupplementsRouteImport } from './routes/change-details.supplements'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRangeRoute = AgeRangeRouteImport.update({
  id: '/age-range',
  path: '/age-range',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeDetailsRoute = ChangeDetailsRouteImport.update({
  id: '/change-details',
  path: '/change-details',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyStageRoute = JourneyStageRouteImport.update({
  id: '/journey-stage',
  path: '/journey-stage',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/onboarding-step-3',
  path: '/onboarding-step-3',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/onboarding-step-4',
  path: '/onboarding-step-4',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitionRoute = TransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeDetailsIndexRoute = ChangeDetailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChangeDetailsRoute,
} as any)
const ChangeDetailsDietaryChangesRoute =
  ChangeDetailsDietaryChangesRouteImport.update({
    id: '/dietary-changes',
    path: '/dietary-changes',
    getParentRoute: () => ChangeDetailsRoute,
  } as any)
const ChangeDetailsPhysicalActivityRoute =
  ChangeDetailsPhysicalActivityRouteImport.update({
    id: '/physical-activity',
    path: '/physical-activity',
    getParentRoute: () => ChangeDetailsRoute,
  } as any)
const ChangeDetailsSleepRoutineRoute =
  ChangeDetailsSleepRoutineRouteImport.update({
    id: '/sleep-routine',
    path: '/sleep-routine',
    getParentRoute: () => ChangeDetailsRoute,
  } as any)
const ChangeDetailsSupplementsRoute =
  ChangeDetailsSupplementsRouteImport.update({
    id: '/supplements',
    path: '/supplements',
    getParentRoute: () => ChangeDetailsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age-range': typeof AgeRangeRoute
  '/change-details': typeof ChangeDetailsRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/journey-stage': typeof JourneyStageRoute
  '/onboarding-step-3': typeof OnboardingStep3Route
  '/onboarding-step-4': typeof OnboardingStep4Route
  '/transition': typeof TransitionRoute
  '/welcome': typeof WelcomeRoute
  '/change-details/dietary-changes': typeof ChangeDetailsDietaryChangesRoute
  '/change-details/physical-activity': typeof ChangeDetailsPhysicalActivityRoute
  '/change-details/sleep-routine': typeof ChangeDetailsSleepRoutineRoute
  '/change-details/supplements': typeof ChangeDetailsSupplementsRoute
  '/change-details/': typeof ChangeDetailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age-range': typeof AgeRangeRoute
  '/check-in': typeof CheckInRoute
  '/journey-stage': typeof JourneyStageRoute
  '/onboarding-step-3': typeof OnboardingStep3Route
  '/onboarding-step-4': typeof OnboardingStep4Route
  '/transition': typeof TransitionRoute
  '/welcome': typeof WelcomeRoute
  '/change-details/dietary-changes': typeof ChangeDetailsDietaryChangesRoute
  '/change-details/physical-activity': typeof ChangeDetailsPhysicalActivityRoute
  '/change-details/sleep-routine': typeof ChangeDetailsSleepRoutineRoute
  '/change-details/supplements': typeof ChangeDetailsSupplementsRoute
  '/change-details': typeof ChangeDetailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/age-range': typeof AgeRangeRoute
  '/change-details': typeof ChangeDetailsRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/journey-stage': typeof JourneyStageRoute
  '/onboarding-step-3': typeof OnboardingStep3Route
  '/onboarding-step-4': typeof OnboardingStep4Route
  '/transition': typeof TransitionRoute
  '/welcome': typeof WelcomeRoute
  '/change-details/dietary-changes': typeof ChangeDetailsDietaryChangesRoute
  '/change-details/physical-activity': typeof ChangeDetailsPhysicalActivityRoute
  '/change-details/sleep-routine': typeof ChangeDetailsSleepRoutineRoute
  '/change-details/supplements': typeof ChangeDetailsSupplementsRoute
  '/change-details/': typeof ChangeDetailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/age-range'
    | '/change-details'
    | '/check-in'
    | '/journey-stage'
    | '/onboarding-step-3'
    | '/onboarding-step-4'
    | '/transition'
    | '/welcome'
    | '/change-details/dietary-changes'
    | '/change-details/physical-activity'
    | '/change-details/sleep-routine'
    | '/change-details/supplements'
    | '/change-details/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age-range'
    | '/check-in'
    | '/journey-stage'
    | '/onboarding-step-3'
    | '/onboarding-step-4'
    | '/transition'
    | '/welcome'
    | '/change-details/dietary-changes'
    | '/change-details/physical-activity'
    | '/change-details/sleep-routine'
    | '/change-details/supplements'
    | '/change-details'
  id:
    | '__root__'
    | '/'
    | '/age-range'
    | '/change-details'
    | '/check-in'
    | '/journey-stage'
    | '/onboarding-step-3'
    | '/onboarding-step-4'
    | '/transition'
    | '/welcome'
    | '/change-details/dietary-changes'
    | '/change-details/physical-activity'
    | '/change-details/sleep-routine'
    | '/change-details/supplements'
    | '/change-details/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeRangeRoute: typeof AgeRangeRoute
  ChangeDetailsRoute: typeof ChangeDetailsRouteWithChildren
  CheckInRoute: typeof CheckInRoute
  JourneyStageRoute: typeof JourneyStageRoute
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  TransitionRoute: typeof TransitionRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-range': {
      id: '/age-range'
      path: '/age-range'
      fullPath: '/age-range'
      preLoaderRoute: typeof AgeRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-details': {
      id: '/change-details'
      path: '/change-details'
      fullPath: '/change-details'
      preLoaderRoute: typeof ChangeDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey-stage': {
      id: '/journey-stage'
      path: '/journey-stage'
      fullPath: '/journey-stage'
      preLoaderRoute: typeof JourneyStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-step-3': {
      id: '/onboarding-step-3'
      path: '/onboarding-step-3'
      fullPath: '/onboarding-step-3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-step-4': {
      id: '/onboarding-step-4'
      path: '/onboarding-step-4'
      fullPath: '/onboarding-step-4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transition': {
      id: '/transition'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof TransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-details/': {
      id: '/change-details/'
      path: '/'
      fullPath: '/change-details/'
      preLoaderRoute: typeof ChangeDetailsIndexRouteImport
      parentRoute: typeof ChangeDetailsRoute
    }
    '/change-details/dietary-changes': {
      id: '/change-details/dietary-changes'
      path: '/dietary-changes'
      fullPath: '/change-details/dietary-changes'
      preLoaderRoute: typeof ChangeDetailsDietaryChangesRouteImport
      parentRoute: typeof ChangeDetailsRoute
    }
    '/change-details/physical-activity': {
      id: '/change-details/physical-activity'
      path: '/physical-activity'
      fullPath: '/change-details/physical-activity'
      preLoaderRoute: typeof ChangeDetailsPhysicalActivityRouteImport
      parentRoute: typeof ChangeDetailsRoute
    }
    '/change-details/sleep-routine': {
      id: '/change-details/sleep-routine'
      path: '/sleep-routine'
      fullPath: '/change-details/sleep-routine'
      preLoaderRoute: typeof ChangeDetailsSleepRoutineRouteImport
      parentRoute: typeof ChangeDetailsRoute
    }
    '/change-details/supplements': {
      id: '/change-details/supplements'
      path: '/supplements'
      fullPath: '/change-details/supplements'
      preLoaderRoute: typeof ChangeDetailsSupplementsRouteImport
      parentRoute: typeof ChangeDetailsRoute
    }
  }
}

interface ChangeDetailsRouteChildren {
  ChangeDetailsDietaryChangesRoute: typeof ChangeDetailsDietaryChangesRoute
  ChangeDetailsPhysicalActivityRoute: typeof ChangeDetailsPhysicalActivityRoute
  ChangeDetailsSleepRoutineRoute: typeof ChangeDetailsSleepRoutineRoute
  ChangeDetailsSupplementsRoute: typeof ChangeDetailsSupplementsRoute
  ChangeDetailsIndexRoute: typeof ChangeDetailsIndexRoute
}

const ChangeDetailsRouteChildren: ChangeDetailsRouteChildren = {
  ChangeDetailsDietaryChangesRoute: ChangeDetailsDietaryChangesRoute,
  ChangeDetailsPhysicalActivityRoute: ChangeDetailsPhysicalActivityRoute,
  ChangeDetailsSleepRoutineRoute: ChangeDetailsSleepRoutineRoute,
  ChangeDetailsSupplementsRoute: ChangeDetailsSupplementsRoute,
  ChangeDetailsIndexRoute: ChangeDetailsIndexRoute,
}

const ChangeDetailsRouteWithChildren = ChangeDetailsRoute._addFileChildren(
  ChangeDetailsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeRangeRoute: AgeRangeRoute,
  ChangeDetailsRoute: ChangeDetailsRouteWithChildren,
  CheckInRoute: CheckInRoute,
  JourneyStageRoute: JourneyStageRoute,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  TransitionRoute: TransitionRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
