/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgeRangeRouteImport } from './routes/age-range'
import { Route as JourneyStageRouteImport } from './routes/journey-stage'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding-step-3'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding-step-4'
import { Route as WelcomeRouteImport } from './routes/welcome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRangeRoute = AgeRangeRouteImport.update({
  id: '/age-range',
  path: '/age-range',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyStageRoute = JourneyStageRouteImport.update({
  id: '/journey-stage',
  path: '/journey-stage',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/onboarding-step-3',
  path: '/onboarding-step-3',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/onboarding-step-4',
  path: '/onboarding-step-4',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age-range': typeof AgeRangeRoute
  '/journey-stage': typeof JourneyStageRoute
  '/onboarding-step-3': typeof OnboardingStep3Route
  '/onboarding-step-4': typeof OnboardingStep4Route
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age-range': typeof AgeRangeRoute
  '/journey-stage': typeof JourneyStageRoute
  '/onboarding-step-3': typeof OnboardingStep3Route
  '/onboarding-step-4': typeof OnboardingStep4Route
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/age-range': typeof AgeRangeRoute
  '/journey-stage': typeof JourneyStageRoute
  '/onboarding-step-3': typeof OnboardingStep3Route
  '/onboarding-step-4': typeof OnboardingStep4Route
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/age-range'
    | '/journey-stage'
    | '/onboarding-step-3'
    | '/onboarding-step-4'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age-range'
    | '/journey-stage'
    | '/onboarding-step-3'
    | '/onboarding-step-4'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/age-range'
    | '/journey-stage'
    | '/onboarding-step-3'
    | '/onboarding-step-4'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeRangeRoute: typeof AgeRangeRoute
  JourneyStageRoute: typeof JourneyStageRoute
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-range': {
      id: '/age-range'
      path: '/age-range'
      fullPath: '/age-range'
      preLoaderRoute: typeof AgeRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey-stage': {
      id: '/journey-stage'
      path: '/journey-stage'
      fullPath: '/journey-stage'
      preLoaderRoute: typeof JourneyStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-step-3': {
      id: '/onboarding-step-3'
      path: '/onboarding-step-3'
      fullPath: '/onboarding-step-3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-step-4': {
      id: '/onboarding-step-4'
      path: '/onboarding-step-4'
      fullPath: '/onboarding-step-4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeRangeRoute: AgeRangeRoute,
  JourneyStageRoute: JourneyStageRoute,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
